cache:
  directories:
    - $HOME/.m2

dist: xenial

env:
  - COMPILE_IMAGE_TAG=11-jdk-slim TEST_IMAGE_TAG=12-jdk-alpine

language: minimal

services:
  - docker

script:
  - ./docker-build.sh $COMPILE_IMAGE_TAG $TEST_IMAGE_TAG
