cache:
  directories:
    - $HOME/.m2

dist: xenial

env:
  - COMPILE_IMAGE_TAG=11-jdk-slim TEST_IMAGE_TAG=12-jdk-alpine

language: minimal

# Run the build in Docker to shield it from changes in the Travis environment:
services:
  - docker

script:
  - ./docker-mvnw $COMPILE_IMAGE_TAG clean package -DskipTests=true
  - ./docker-mvnw $TEST_IMAGE_TAG verify
