cache:
  directories:
    - $HOME/.m2

dist: xenial

env:
  - COMPILE_IMAGE_TAG=1.2.8-jdk11 TEST_IMAGE_TAG=1.2.8-jdk12

language: minimal

services:
  - docker

script:
  - ./docker-build.sh $COMPILE_IMAGE_TAG $TEST_IMAGE_TAG
