#!/bin/sh
IMAGE_TAG="$1"
shift
[ -z "$IMAGE_TAG" ] && { echo 'Usage: docker-mvnw $IMAGE_TAG [...]'; exit 1; }
set -x
exec docker run \
    --interactive \
    --rm \
    --tty \
    --volume $HOME/.m2:/root/.m2 \
    --volume "`pwd`:/workdir" \
    --workdir /workdir \
    "openjdk:$IMAGE_TAG" \
    ./mvnw $@
